POST http://localhost:5000/api/split/create
Content-Type: application/json

{
    "title": "split title",
    "amount": 2000,
    "category":"Rent",
    "participants": [
        { "name": "meki", 
        "email": "email@gmail.com", 
        "paid":false
        },
        { "name": "meki", "email": "emailnhgb@gmail.com", "paid":true }
    ]
}